(()=>{"use strict";
const C=window.APP_CONFIG||{}, $=id=>document.getElementById(id);
const markets={"OTC":["EUR/USD (OTC)","GBP/USD (OTC)","USD/JPY (OTC)","AUD/USD (OTC)","USD/CAD (OTC)","USD/CHF (OTC)","NZD/USD (OTC)","EUR/GBP (OTC)","EUR/JPY (OTC)","GBP/JPY (OTC)","AUD/JPY (OTC)"],"FOREX":["EUR/USD","GBP/USD","USD/JPY","USD/CHF","AUD/USD","USD/CAD","NZD/USD","EUR/GBP","EUR/JPY","GBP/JPY"],"CRYPTO":["BTC/USD","ETH/USD","LTC/USD","XRP/USD"],"COMMODITIES":["GOLD","SILVER","BRENT OIL","WTI OIL"],"INDICES":["US 500","US TECH 100","DOW JONES","DAX","FTSE 100"]};
const S={market:"EUR/USD (OTC)",tf:1,price:1.0842,candles:[],sound:true,signal:null,user:null};
const chart=$("chart"),ctx=chart.getContext("2d");
const ADMIN_KEY=C.ADMIN_KEY||"1028";
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random();
function pad(n){return String(n).padStart(2,"0")} function now(){return new Date()}
function sec(){return S.tf*60} function start(){let t=Math.floor(now().getTime()/1000);return new Date((t-t%sec())*1000)}
function remain(){return Math.max(0,sec()-Math.floor((now()-start())/1000))}
function fmt(s){return pad(Math.floor(s/60))+":"+pad(s%60)} function next(){return new Date(start().getTime()+sec()*1000)}
function tm(d){return pad(d.getHours())+":"+pad(d.getMinutes())+":"+pad(d.getSeconds())} function sm(d){return pad(d.getHours())+":"+pad(d.getMinutes())}
function speak(t){if(!S.sound||!speechSynthesis)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang="bn-BD";u.rate=.93;speechSynthesis.speak(u)}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").classList.remove("show"),2500)}
function buildMenu(f=""){let h=$("marketGroups");h.innerHTML="";f=f.toLowerCase();for(let [g,a] of Object.entries(markets)){let x=a.filter(v=>v.toLowerCase().includes(f));if(!x.length)continue;let d=document.createElement("div");d.innerHTML="<h3>"+g+"</h3>";x.forEach(v=>{let b=document.createElement("button");b.className="market-item";b.innerHTML="<span>"+v+"</span><small>"+(v.includes("(OTC)")?"OTC":"LIVE")+"</small>";b.onclick=()=>{S.market=v;$("selectedMarket").textContent=v;$("marketButtonText").textContent=v;$("sideMarket").textContent=v;$("marketMenu").classList.add("hidden");seed();speak(v+" selected");};d.appendChild(b)});h.appendChild(d)}}
function base(){if(S.market.includes("JPY"))return 157.2;if(S.market.includes("GOLD"))return 2500;if(S.market.includes("BTC"))return 110000;if(S.market.includes("ETH"))return 4200;return 1.0842}
function seed(){S.price=base();S.candles=[];let p=S.price;for(let i=0;i<70;i++){let o=p,step=p>10000?80:p>1000?8:p>100?.35:p>10?.08:.0012,m=(Math.random()-.5)*step,c=o+m,h=Math.max(o,c)+Math.abs(m)*(.3+Math.random()),l=Math.min(o,c)-Math.abs(m)*(.3+Math.random());S.candles.push({o,c,h,l});p=c}draw()}
function draw(){let r=chart.getBoundingClientRect(),d=devicePixelRatio||1;if(!r.width)return;chart.width=r.width*d;chart.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);let W=r.width,H=r.height;ctx.clearRect(0,0,W,H);ctx.strokeStyle="rgba(130,160,180,.1)";for(let i=1;i<6;i++){let y=i*H/6;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}let cs=S.candles.slice(-42),vs=cs.flatMap(c=>[c.h,c.l]),mn=Math.min(...vs),mx=Math.max(...vs),pv=(mx-mn)*.12||1;mn-=pv;mx+=pv;let y=v=>H-(v-mn)/(mx-mn)*H,st=W/cs.length,b=Math.max(4,st*.46);cs.forEach((c,i)=>{let x=i*st+st/2,yo=y(c.o),yc=y(c.c);ctx.strokeStyle=c.c>=c.o?"#16e39a":"#ff3f57";ctx.beginPath();ctx.moveTo(x,y(c.h));ctx.lineTo(x,y(c.l));ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.fillRect(x-b/2,Math.min(yo,yc),b,Math.max(2,Math.abs(yc-yo)))})}
function update(){let d=now();$("liveClock").textContent=tm(d);$("countdown").textContent=fmt(remain());$("sideCountdown").textContent=fmt(remain());$("nextCandleTime").textContent=tm(next());$("sideNext").textContent=tm(next());$("signalEntryTime").textContent=sm(next());$("candleLabel").textContent=S.tf+" মিনিট candle";$("sideTimeframe").textContent=S.tf+" minute";$("price").textContent=S.price>=10000?S.price.toFixed(2):S.price>=100?S.price.toFixed(3):S.price.toFixed(5);draw()}
function isLogged(){return S.user&&Date.now()<S.user.expires}
function save(){localStorage.fx_user=JSON.stringify(S.user||null)}
function load(){try{S.user=JSON.parse(localStorage.fx_user||"null")}catch{}if(S.user&&Date.now()>=S.user.expires){S.user=null;save();toast("Login key expired")}}
function open(id){$(id).classList.remove("hidden")} function close(id){$(id).classList.add("hidden")}
function showLogin(){open("loginModal");$("loginKey").focus()}
function randomKey(){let chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";let s="";for(let i=0;i<12;i++)s+=chars[Math.floor(Math.random()*chars.length)];return s.slice(0,5)+"-"+s.slice(5,9)+"-"+s.slice(9)}
function getKeys(){try{return JSON.parse(localStorage.fx_keys||"[]")}catch{return[]}} function setKeys(a){localStorage.fx_keys=JSON.stringify(a)}
function login(key){key=key.trim();if(key===ADMIN_KEY){S.user={key:"ADMIN",role:"admin",expires:Date.now()+365*864e5,device:uid()};save();close("loginModal");open("adminModal");renderKeys();toast("Admin login successful");return}
let a=getKeys(),k=a.find(x=>x.key===key&&!x.deleted&&Date.now()<x.expires);if(!k){$("loginError").textContent="Key ভুল, expired অথবা delete করা হয়েছে।";return}
S.user={key:k.key,role:"user",expires:k.expires,device:uid()};save();localStorage.setItem("fx_session_"+k.key, S.user.device);close("loginModal");$("loginError").textContent="";$("assistantStatus").textContent="Login active — dual AI signal ready.";toast("Login successful")}
function renderKeys(){let a=getKeys();$("keysList").innerHTML=a.length?"":"<div class='empty'>এখনও কোনো key নেই।</div>";a.filter(x=>!x.deleted).forEach(x=>{let row=document.createElement("div");row.className="key-row";let left=document.createElement("div");left.innerHTML="<b>"+x.key+"</b><small>"+x.minutes+" মিনিট • expire: "+new Date(x.expires).toLocaleString("bn-BD")+"</small>";let devices=localStorage.getItem("fx_session_"+x.key)?1:0;let b=document.createElement("button");b.className="danger";b.textContent="Logout ("+devices+")";b.onclick=()=>{localStorage.removeItem("fx_session_"+x.key);toast("Device logout signal sent")};let del=document.createElement("button");del.className="delete";del.textContent="Delete";del.onclick=()=>{x.deleted=true;setKeys(a);renderKeys()};row.append(left,b,del);$("keysList").appendChild(row)})}
function checks(){return["Trend direction","EMA/SMA alignment","RSI momentum","MACD momentum","Support / Resistance","Volatility","Candle body & wick","Doji / Hammer / Engulfing","Breakout / Pullback","Higher High / Lower Low","Multi-timeframe context","OpenAI reasoning","Gemini reasoning","Final agreement"].map(x=>"<span>✓ "+x+"</span>").join("")}
async function aiCall(kind,payload){let key=kind==="openai"?C.OPENAI_API_KEY:C.GEMINI_API_KEY;if(!key)return null;try{if(kind==="openai"){let r=await fetch(C.OPENAI_ENDPOINT||"https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+key},body:JSON.stringify({model:C.OPENAI_MODEL||"gpt-5.6-luna",input:"Analyze this market snapshot in Bengali. Return JSON only: {direction:'UP'|'DOWN'|'NEUTRAL',confidence:0-100,profit:0-100,loss:0-100,reason:'...'} Snapshot:"+JSON.stringify(payload)})});let j=await r.json();let t=j.output_text||"";return JSON.parse(t.match(/\{[\s\S]*\}/)?.[0]||"null")}else{let url=(C.GEMINI_ENDPOINT||"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent")+"?key="+encodeURIComponent(key);let r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:"বাংলায় JSON only. Analyze snapshot; return direction UP/DOWN/NEUTRAL, confidence, profit, loss, reason. "+JSON.stringify(payload)}]}]})});let j=await r.json(),t=j.candidates?.[0]?.content?.parts?.[0]?.text||"";return JSON.parse(t.match(/\{[\s\S]*\}/)?.[0]||"null")}}catch{return null}}
async function signal(){if(!isLogged()){showLogin();return}let box=$("analysisBox");box.classList.remove("hidden");$("signalBtn").disabled=true;$("openaiStatus").textContent="Market structure + indicators...";$("geminiStatus").textContent="Candles + pattern context...";$("checks").innerHTML=checks();let completed=S.candles.slice(0,-1).slice(-12),bull=completed.filter(c=>c.c>=c.o).length,bear=completed.length-bull,last=completed.at(-1),range=last.h-last.l,body=Math.abs(last.c-last.o);let heuristic={direction:bull>=bear?"UP":"DOWN",confidence:Math.round(52+Math.abs(bull-bear)*3),profit:Math.round(55+Math.abs(bull-bear)*2),loss:Math.round(45-Math.min(20,Math.abs(bull-bear)*2)),reason:"Completed candle trend, body/wick and momentum"};let payload={market:S.market,timeframe:S.tf,currentPrice:S.price,completedCandles:completed,bodyRatio:range?body/range:0};let [oa,ge]=await Promise.all([aiCall("openai",payload),aiCall("gemini",payload)]);$("openaiStatus").textContent=oa?"Analysis complete":"API key না থাকায় local analysis";$("geminiStatus").textContent=ge?"Analysis complete":"API key না থাকায় local analysis";await new Promise(r=>setTimeout(r,1200));let A=oa||heuristic,B=ge||heuristic;let same=A.direction===B.direction&&A.direction!=="NEUTRAL";let final=same?A.direction:"WAIT";let conf=same?Math.round((+A.confidence+ +B.confidence)/2):Math.max(0,Math.round(Math.min(+A.confidence||50,+B.confidence||50)-12));S.signal={direction:final,entry:next()};let card=$("signalCard");card.className="signal-card "+(final==="UP"?"up-card":final==="DOWN"?"down-card":"wait-card");$("signalDirection").textContent=final==="UP"?"▲ UP":final==="DOWN"?"▼ DOWN":"⏸ WAIT";let profit=same?Math.round(((+A.profit||55)+(+B.profit||55))/2):0,loss=same?Math.round(((+A.loss||45)+(+B.loss||45))/2):100;let reason=same?"OpenAI ও Gemini একই direction দিয়েছে।":"দুই AI একই direction দেয়নি, তাই নিরাপত্তার জন্য WAIT."; $("signalText").textContent=reason+" Confidence "+conf+"%. সম্ভাব্য লাভ ~"+profit+"%, সম্ভাব্য loss ~"+loss+"% (estimate).";$("assistantStatus").textContent=final==="WAIT"?"AI disagreement — WAIT":"Dual AI "+final+" confirmed.";speak(final==="WAIT"?"দুইটি এআই একই দিক দেয়নি। ওয়েট সিগন্যাল।":"ফাইনাল "+final+" সিগন্যাল। কনফিডেন্স "+conf+" শতাংশ। সম্ভাব্য লাভ "+profit+" শতাংশ, সম্ভাব্য লস "+loss+" শতাংশ।");$("signalBtn").disabled=false;setTimeout(()=>box.classList.add("hidden"),3500)}
function chat(){let t=$("chatInput").value.trim();if(!t)return;$("chatInput").value="";addChat("user",t);let r="আমি "+S.market+" এর "+S.tf+" মিনিট candle দেখছি। Signal-এর জন্য trend, EMA, RSI, MACD, support-resistance, volatility ও candlestick pattern দেখা হয়।";addChat("bot",r);speak(r)}
function addChat(w,t){let e=document.createElement("div");e.className="chat-msg "+w;e.textContent=t;$("chat").appendChild(e);$("chat").scrollTop=$("chat").scrollHeight}
$("signalBtn").onclick=signal;$("loginFab").onclick=()=>{if(isLogged()){S.user=null;save();toast("Logout successful");$("loginFab").textContent="🔐 Login";$("assistantStatus").textContent="Login করে analysis শুরু করুন।"}else showLogin()};$("loginSubmit").onclick=()=>login($("loginKey").value);$("loginKey").onkeydown=e=>{if(e.key==="Enter")login($("loginKey").value)};$("adminLogout").onclick=()=>{S.user=null;save();close("adminModal");$("loginFab").textContent="🔐 Login";toast("Admin logout")};$("generateKey").onclick=()=>{if(!S.user||S.user.role!=="admin")return;let m=+$("keyDuration").value,a=getKeys(),k={key:randomKey(),minutes:m,expires:Date.now()+m*60000,created:Date.now(),deleted:false};a.push(k);setKeys(a);localStorage.setItem("fx_session_"+k.key,"1");renderKeys();toast("New key generated: "+k.key)};$("marketButton").onclick=()=>{$("marketMenu").classList.toggle("hidden");buildMenu($("marketSearch").value)};$("marketSearch").oninput=e=>buildMenu(e.target.value);document.querySelectorAll(".tf").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tf").forEach(x=>x.classList.remove("active"));b.classList.add("active");S.tf=+b.dataset.tf});$("sendBtn").onclick=chat;$("chatInput").onkeydown=e=>{if(e.key==="Enter")chat()};$("speakBtn").onclick=()=>speak("বাংলায় ভয়েস অ্যাসিস্ট্যান্ট চালু আছে।");$("soundBtn").onclick=()=>{S.sound=!S.sound;$("soundBtn").textContent=S.sound?"🔊":"🔇"};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>close(b.dataset.close));window.onclick=e=>{if(e.target.classList?.contains("modal"))e.target.classList.add("hidden")};
load();$("loginFab").textContent=isLogged()?"↪ Logout":"🔐 Login";if(isLogged())$("assistantStatus").textContent="Login active — dual AI signal ready.";buildMenu();seed();update();setInterval(()=>{if(S.user&&Date.now()>=S.user.expires){S.user=null;save();$("loginFab").textContent="🔐 Login";toast("Login key expired — logged out");}},1000);setInterval(update,250);window.addEventListener("resize",draw);
})();